version: 2
jobs:
  build:
    working_directory: ~/katie
    docker:
      - image: gradle:4.9-jdk8
    steps:
      - checkout
      - restore_cache:
          key: circleci-katie-{{ checksum "build.gradle" }}
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: circleci-katie-{{ checksum "build.gradle" }}
      - run: gradle build
      - run: gradle test
  docker-build:
    docker:
      - image: docker:17.07.0   # (1)
    working_directory: ~/katie
    steps:
      - checkout
      - setup_remote_docker
      # build and push Docker image
      - deploy:
          command: |
            TAG=$CIRCLE_SHA1
            docker build --build-arg=JITPACK_TOKEN="$JITPACK_TOKEN" -t zensum/katie:latest -t zensum/katie:$TAG .
            docker login -u $HUB_USERNAME -p $HUB_PASSWORD
            docker push zensum/katie:$TAG
            docker push zensum/katie:latest
workflows:
  version: 2
  build_and_docker:
    jobs:
      - build:
          context: org-global
      - docker-build:
          context: org-global
          requires:
            - build
          filters:
            branches:
              only: master
